### ISSUE TITLE
Message is always sent twice

### ISSUE THREAD

**Issue by suchasurge** [wjessop/Scamp#14]
Hi.

I tried the basic example and everthing works except the messages from the bot.
The bot always sent 2 messages. And it is logged in twice.

I copied the example in my local folder, installed the gem and start with `ruby example.rb` 

Thx
Frank

**Comment by wjessop** [comment]
In bot.connect! are you specifying the room to join twice at all?

**Comment by suchasurge** [comment]
Ahhh.

I followed your example: `scamp.connect!([293788, "Monitoring"])` 

But when I take this one everything is ok: `scamp.connect!([293788])` 

I didn't realize that 293788 and "Monitoring" should not be the same room.

Thx
